// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmJ1LbxL1OMeNNL-i7Du-X2joN-DTD6jk',
    appId: '1:582057991572:android:10afef888fd78978d60381',
    messagingSenderId: '582057991572',
    projectId: 'insta-clone-riverpod-learning',
    storageBucket: 'insta-clone-riverpod-learning.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXJtvBE_QNw1Yfi3NZQLhvSTFrLklzWi0',
    appId: '1:582057991572:ios:faa655f4f4cd11e7d60381',
    messagingSenderId: '582057991572',
    projectId: 'insta-clone-riverpod-learning',
    storageBucket: 'insta-clone-riverpod-learning.appspot.com',
    androidClientId: '582057991572-0duhcmjjic3mj2spf1r0faiuvfv3bnh7.apps.googleusercontent.com',
    iosClientId: '582057991572-56hnudusrgs4604mlbhe7s5tvgaj9ecu.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeFoodApp',
  );
}
